.Dd $Mdocdate$
.Dt UNINSTALL.SH 1
.Os
.Sh NAME
.Nm uninstall.sh
.Nd remove the Spacecentricity keymap symlink from a QMK checkout
.Sh SYNOPSIS
.Nm
.Op Ar keymap_name
.Op Fl h | Fl -help
.Sh DESCRIPTION
.Nm
is an optional POSIX-compliant script that removes the symbolic link from your
QMK keymaps directory that was created by
.Xr install.sh 1 .
.Pp
This script does
.Em not
delete any files from this repository; it only removes the symlink
inside the QMK tree.
.Pp
This script also removes any optional man pages previously installed by
.Xr install_man.sh 1 .
.Pp
By default:
.Bl -bullet
.It
The keymap name is
.Sq spacecentricity .
.It
The QMK checkout is assumed to be at
.Pa $HOME/qmk_firmware .
.El
.Pp
These defaults may be overridden:
.Bl -tag -width Ds
.It Keymap name
Passed as a positional argument:
.Bd -literal -offset indent
uninstall.sh my_keymap_name
.Ed
.It QMK directory
Set via the
.Ev QMK_PATH
environment variable:
.Bd -literal -offset indent
QMK_PATH=/path/to/qmk_firmware uninstall.sh
.Ed
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl -help
Show the help message and exit.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev QMK_PATH
Path to your QMK firmware checkout.
Defaults to
.Pa $HOME/qmk_firmware .
.El
.Sh EXAMPLES
.Bd -literal
uninstall.sh
uninstall.sh my_keymap_name
QMK_PATH=~/Projects/qmk_firmware uninstall.sh
.Ed
.Pp
After removal, the keymap will no longer appear in:
.Bd -literal -offset indent
keyboards/<keyboard>/<revision>/keymaps/
.Ed
.Sh SEE ALSO
.Xr build.sh 1 ,
.Xr install.sh 1 ,
.Xr install_man.sh 1 ,
.Xr license_headers.sh 1 ,
.Xr spacecentricity 7
.Sh AUTHORS
.An LittleWalter
.Sh SOURCE CODE
.Lk https://github.com/LittleWalter/spacecentricity-mk47
